/* eslint-disable @typescript-eslint/no-explicit-any */
import { describe, it, expect } from "vitest";
import { generateTypeScript } from "../lib/ts-generator";

describe("TypeScript Interface Generator", () => {
  const sampleSchema = {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid", "x-faker": "string.uuid" },
      username: { type: "string", "x-faker": "internet.username" },
      age: { type: "integer", minimum: 0 },
      email: { type: ["string", "null"] },
    },
    required: ["id", "username", "age"],
  };

  it("should compile a JSON Schema to TypeScript interface strings", async () => {
    const tsCode = await generateTypeScript(sampleSchema, {
      typeName: "User",
      bannerComment: false,
    });

    expect(tsCode).toContain("export interface User {");
    expect(tsCode).toContain("id: string;");
    expect(tsCode).toContain("username: string;");
    expect(tsCode).toContain("age: number;");
    expect(tsCode).toContain("email?: string | null;");
  });

  it("should strip out custom 'x-faker' and format keys from generated TS comments", async () => {
    const tsCode = await generateTypeScript(sampleSchema, {
      typeName: "User",
      bannerComment: false,
    });

    expect(tsCode).not.toContain("x-faker");
    expect(tsCode).not.toContain("string.uuid");
  });

  it("should include a banner comment when requested", async () => {
    const tsCode = await generateTypeScript(sampleSchema, {
      typeName: "User",
      bannerComment: true,
    });

    expect(tsCode).toContain("Auto-generated by Fack API");
  });

  it("should recover gracefully from compilation failures and output fallback definition", async () => {
    // Passing a corrupt schema that causes json-schema-to-typescript compilation to crash
    const corruptSchema = {
      type: "object",
      properties: {
        badField: { $ref: "#/definitions/missing" },
      },
    } as any;

    const tsCode = await generateTypeScript(corruptSchema, {
      typeName: "FallbackInterface",
      bannerComment: false,
    });

    expect(tsCode).toContain("TypeScript generation failed");
    expect(tsCode).toContain("export interface FallbackInterface {");
    expect(tsCode).toContain("[key: string]: unknown;");
  });

  it("should output index signatures when additionalProperties is enabled", async () => {
    const tsCodeWithout = await generateTypeScript(sampleSchema, {
      typeName: "WithoutAdditional",
      bannerComment: false,
      additionalProperties: false,
    });

    const tsCodeWith = await generateTypeScript(sampleSchema, {
      typeName: "WithAdditional",
      bannerComment: false,
      additionalProperties: true,
    });

    expect(tsCodeWithout).not.toContain("[k: string]: any;");
    expect(tsCodeWith).toContain("[k: string]: any;");
  });

  it("should support array of objects schema compiler mapping", async () => {
    const arraySchema = {
      type: "object",
      properties: {
        users: {
          type: "array",
          items: {
            type: "object",
            properties: {
              name: { type: "string" },
            },
            required: ["name"],
          },
        },
      },
      required: ["users"],
    };

    const tsCode = await generateTypeScript(arraySchema, {
      typeName: "Org",
      bannerComment: false,
    });

    expect(tsCode).toContain("users: {");
    expect(tsCode).toContain("name: string;");
  });
});
