// This file is auto-generated by running a extraction script on @faker-js/faker.
// It contains static provider definitions to avoid bundling the massive @faker-js/faker library on the client side.

export interface FakerProvider {
  value: string;
  label: string;
  example: string;
  category: string;
}

export const staticProviderDefinitions: FakerProvider[] = [
  {
    "value": "airline.aircraftType",
    "label": "Aircraft Type",
    "example": "narrowbody",
    "category": "Airline"
  },
  {
    "value": "airline.airline",
    "label": "Airline",
    "example": "{\"name\":\"EcoJet\",\"iataCode\":\"8J\"}",
    "category": "Airline"
  },
  {
    "value": "airline.airplane",
    "label": "Airplane",
    "example": "{\"name\":\"Ilyushin IL114\",\"iataTypeCode\":\"I14\"}",
    "category": "Airline"
  },
  {
    "value": "airline.airport",
    "label": "Airport",
    "example": "{\"name\":\"Frankfurt am Main Airport\",\"iataCode\":\"FRA\"}",
    "category": "Airline"
  },
  {
    "value": "airline.flightNumber",
    "label": "Flight Number",
    "example": "9218",
    "category": "Airline"
  },
  {
    "value": "airline.recordLocator",
    "label": "Record Locator",
    "example": "GDEJMR",
    "category": "Airline"
  },
  {
    "value": "airline.seat",
    "label": "Seat",
    "example": "13C",
    "category": "Airline"
  },
  {
    "value": "animal.bear",
    "label": "Bear",
    "example": "Giant panda",
    "category": "Animal"
  },
  {
    "value": "animal.bird",
    "label": "Bird",
    "example": "Olive-backed Pipit",
    "category": "Animal"
  },
  {
    "value": "animal.cat",
    "label": "Cat",
    "example": "Minskin",
    "category": "Animal"
  },
  {
    "value": "animal.cetacean",
    "label": "Cetacean",
    "example": "Clymene Dolphin",
    "category": "Animal"
  },
  {
    "value": "animal.cow",
    "label": "Cow",
    "example": "Aubrac",
    "category": "Animal"
  },
  {
    "value": "animal.crocodilia",
    "label": "Crocodilia",
    "example": "American Crocodile",
    "category": "Animal"
  },
  {
    "value": "animal.dog",
    "label": "Dog",
    "example": "Wirehaired Pointing Griffon",
    "category": "Animal"
  },
  {
    "value": "animal.fish",
    "label": "Fish",
    "example": "Yellowhead catfish",
    "category": "Animal"
  },
  {
    "value": "animal.horse",
    "label": "Horse",
    "example": "Frederiksborg Horse",
    "category": "Animal"
  },
  {
    "value": "animal.insect",
    "label": "Insect",
    "example": "Pteromalid wasp",
    "category": "Animal"
  },
  {
    "value": "animal.lion",
    "label": "Lion",
    "example": "Northeast Congo Lion",
    "category": "Animal"
  },
  {
    "value": "animal.petName",
    "label": "Pet Name",
    "example": "Milo",
    "category": "Animal"
  },
  {
    "value": "animal.rabbit",
    "label": "Rabbit",
    "example": "Flemish Giant",
    "category": "Animal"
  },
  {
    "value": "animal.rodent",
    "label": "Rodent",
    "example": "Long-tailed porcupine",
    "category": "Animal"
  },
  {
    "value": "animal.snake",
    "label": "Snake",
    "example": "Stejneger's bamboo pitviper",
    "category": "Animal"
  },
  {
    "value": "animal.type",
    "label": "Type",
    "example": "butterfly",
    "category": "Animal"
  },
  {
    "value": "book.author",
    "label": "Author",
    "example": "Shivaram Parashuram Bhide",
    "category": "Book"
  },
  {
    "value": "book.format",
    "label": "Format",
    "example": "Hardcover",
    "category": "Book"
  },
  {
    "value": "book.genre",
    "label": "Genre",
    "example": "Historical Fiction",
    "category": "Book"
  },
  {
    "value": "book.publisher",
    "label": "Publisher",
    "example": "Horizon Scientific Press",
    "category": "Book"
  },
  {
    "value": "book.series",
    "label": "Series",
    "example": "Little Women",
    "category": "Book"
  },
  {
    "value": "book.title",
    "label": "Title",
    "example": "The King in Yellow",
    "category": "Book"
  },
  {
    "value": "color.cmyk",
    "label": "Cmyk",
    "example": "[0.48,0.43,0.98,0.21]",
    "category": "Color"
  },
  {
    "value": "color.colorByCSSColorSpace",
    "label": "Color By C S S Color Space",
    "example": "[0.0327,0.1176,0.7315]",
    "category": "Color"
  },
  {
    "value": "color.cssSupportedFunction",
    "label": "Css Supported Function",
    "example": "hsla",
    "category": "Color"
  },
  {
    "value": "color.cssSupportedSpace",
    "label": "Css Supported Space",
    "example": "sRGB",
    "category": "Color"
  },
  {
    "value": "color.hsl",
    "label": "Hsl",
    "example": "[88,0.16,0.3]",
    "category": "Color"
  },
  {
    "value": "color.human",
    "label": "Human",
    "example": "violet",
    "category": "Color"
  },
  {
    "value": "color.hwb",
    "label": "Hwb",
    "example": "[174,0.58,0.85]",
    "category": "Color"
  },
  {
    "value": "color.lab",
    "label": "Lab",
    "example": "[0.483643,-36.7595,-57.5193]",
    "category": "Color"
  },
  {
    "value": "color.lch",
    "label": "Lch",
    "example": "[0.270604,82.7,126.5]",
    "category": "Color"
  },
  {
    "value": "color.rgb",
    "label": "Rgb",
    "example": "#0a26a9",
    "category": "Color"
  },
  {
    "value": "color.space",
    "label": "Space",
    "example": "LCh",
    "category": "Color"
  },
  {
    "value": "commerce.department",
    "label": "Department",
    "example": "Tools",
    "category": "Commerce"
  },
  {
    "value": "commerce.isbn",
    "label": "Isbn",
    "example": "978-0-399-08580-2",
    "category": "Commerce"
  },
  {
    "value": "commerce.price",
    "label": "Price",
    "example": "639.99",
    "category": "Commerce"
  },
  {
    "value": "commerce.product",
    "label": "Product",
    "example": "Mouse",
    "category": "Commerce"
  },
  {
    "value": "commerce.productAdjective",
    "label": "Product Adjective",
    "example": "Elegant",
    "category": "Commerce"
  },
  {
    "value": "commerce.productDescription",
    "label": "Product Description",
    "example": "The Kelley Table is the latest in a series of agitated products from Medhurst Group",
    "category": "Commerce"
  },
  {
    "value": "commerce.productMaterial",
    "label": "Product Material",
    "example": "Aluminum",
    "category": "Commerce"
  },
  {
    "value": "commerce.productName",
    "label": "Product Name",
    "example": "Oriental Cotton Sausages",
    "category": "Commerce"
  },
  {
    "value": "commerce.upc",
    "label": "Upc",
    "example": "116763747981",
    "category": "Commerce"
  },
  {
    "value": "company.buzzAdjective",
    "label": "Buzz Adjective",
    "example": "scalable",
    "category": "Company"
  },
  {
    "value": "company.buzzNoun",
    "label": "Buzz Noun",
    "example": "architectures",
    "category": "Company"
  },
  {
    "value": "company.buzzPhrase",
    "label": "Buzz Phrase",
    "example": "mesh cross-platform niches",
    "category": "Company"
  },
  {
    "value": "company.buzzVerb",
    "label": "Buzz Verb",
    "example": "mesh",
    "category": "Company"
  },
  {
    "value": "company.catchPhrase",
    "label": "Catch Phrase",
    "example": "Distributed cloud-native knowledge base",
    "category": "Company"
  },
  {
    "value": "company.catchPhraseAdjective",
    "label": "Catch Phrase Adjective",
    "example": "Compatible",
    "category": "Company"
  },
  {
    "value": "company.catchPhraseDescriptor",
    "label": "Catch Phrase Descriptor",
    "example": "cloud-native",
    "category": "Company"
  },
  {
    "value": "company.catchPhraseNoun",
    "label": "Catch Phrase Noun",
    "example": "frame",
    "category": "Company"
  },
  {
    "value": "company.name",
    "label": "Name",
    "example": "Gottlieb, Nolan and King",
    "category": "Company"
  },
  {
    "value": "database.collation",
    "label": "Collation",
    "example": "utf8_general_ci",
    "category": "Database"
  },
  {
    "value": "database.column",
    "label": "Column",
    "example": "category",
    "category": "Database"
  },
  {
    "value": "database.engine",
    "label": "Engine",
    "example": "InnoDB",
    "category": "Database"
  },
  {
    "value": "database.mongodbObjectId",
    "label": "Mongodb Object Id",
    "example": "5eeff50a7e0f92790a1ef58b",
    "category": "Database"
  },
  {
    "value": "database.type",
    "label": "Type",
    "example": "blob",
    "category": "Database"
  },
  {
    "value": "datatype.boolean",
    "label": "Boolean",
    "example": "false",
    "category": "Datatype"
  },
  {
    "value": "date.anytime",
    "label": "Anytime",
    "example": "\"2026-10-30T17:22:44.043Z\"",
    "category": "Date"
  },
  {
    "value": "date.birthdate",
    "label": "Birthdate",
    "example": "\"1947-10-17T07:29:12.885Z\"",
    "category": "Date"
  },
  {
    "value": "date.future",
    "label": "Future",
    "example": "\"2027-02-17T02:59:09.959Z\"",
    "category": "Date"
  },
  {
    "value": "date.month",
    "label": "Month",
    "example": "June",
    "category": "Date"
  },
  {
    "value": "date.past",
    "label": "Past",
    "example": "\"2026-01-24T10:41:31.951Z\"",
    "category": "Date"
  },
  {
    "value": "date.recent",
    "label": "Recent",
    "example": "\"2026-07-15T00:09:14.702Z\"",
    "category": "Date"
  },
  {
    "value": "date.soon",
    "label": "Soon",
    "example": "\"2026-07-15T19:09:24.053Z\"",
    "category": "Date"
  },
  {
    "value": "date.timeZone",
    "label": "Time Zone",
    "example": "America/Glace_Bay",
    "category": "Date"
  },
  {
    "value": "date.weekday",
    "label": "Weekday",
    "example": "Thursday",
    "category": "Date"
  },
  {
    "value": "finance.accountName",
    "label": "Account Name",
    "example": "Credit Card Account",
    "category": "Finance"
  },
  {
    "value": "finance.accountNumber",
    "label": "Account Number",
    "example": "75579555",
    "category": "Finance"
  },
  {
    "value": "finance.amount",
    "label": "Amount",
    "example": "638.28",
    "category": "Finance"
  },
  {
    "value": "finance.bic",
    "label": "Bic",
    "example": "UAQNGF89BAV",
    "category": "Finance"
  },
  {
    "value": "finance.bitcoinAddress",
    "label": "Bitcoin Address",
    "example": "1jNPgbcU6BrevztFApCZbMcghPoB",
    "category": "Finance"
  },
  {
    "value": "finance.creditCardCVV",
    "label": "Credit Card C V V",
    "example": "313",
    "category": "Finance"
  },
  {
    "value": "finance.creditCardIssuer",
    "label": "Credit Card Issuer",
    "example": "discover",
    "category": "Finance"
  },
  {
    "value": "finance.creditCardNumber",
    "label": "Credit Card Number",
    "example": "3791-135004-80383",
    "category": "Finance"
  },
  {
    "value": "finance.currency",
    "label": "Currency",
    "example": "{\"name\":\"Norwegian Krone\",\"code\":\"NOK\",\"symbol\":\"kr\",\"numericCode\":\"578\"}",
    "category": "Finance"
  },
  {
    "value": "finance.currencyCode",
    "label": "Currency Code",
    "example": "TWD",
    "category": "Finance"
  },
  {
    "value": "finance.currencyName",
    "label": "Currency Name",
    "example": "Pataca",
    "category": "Finance"
  },
  {
    "value": "finance.currencyNumericCode",
    "label": "Currency Numeric Code",
    "example": "044",
    "category": "Finance"
  },
  {
    "value": "finance.currencySymbol",
    "label": "Currency Symbol",
    "example": "$",
    "category": "Finance"
  },
  {
    "value": "finance.ethereumAddress",
    "label": "Ethereum Address",
    "example": "0x45c4efced9d6c1b87ef43ba8cebebe0ed7dac5b9",
    "category": "Finance"
  },
  {
    "value": "finance.iban",
    "label": "Iban",
    "example": "GE60BG3105496088306457",
    "category": "Finance"
  },
  {
    "value": "finance.litecoinAddress",
    "label": "Litecoin Address",
    "example": "LK6gA1KGvKiHZxiRgvTX3CgpuPP",
    "category": "Finance"
  },
  {
    "value": "finance.pin",
    "label": "Pin",
    "example": "3708",
    "category": "Finance"
  },
  {
    "value": "finance.routingNumber",
    "label": "Routing Number",
    "example": "063002650",
    "category": "Finance"
  },
  {
    "value": "finance.transactionDescription",
    "label": "Transaction Description",
    "example": "deposit transaction at Pacocha, Berge and Kassulke using card ending with ****9855 for BWP 277.60 in account ***8399.",
    "category": "Finance"
  },
  {
    "value": "finance.transactionType",
    "label": "Transaction Type",
    "example": "payment",
    "category": "Finance"
  },
  {
    "value": "food.adjective",
    "label": "Adjective",
    "example": "zesty",
    "category": "Food"
  },
  {
    "value": "food.description",
    "label": "Description",
    "example": "Our fresh salmon, slow-cooked to perfection, accompanied by steamed green pepper and a rich, savory gravy.",
    "category": "Food"
  },
  {
    "value": "food.dish",
    "label": "Dish",
    "example": "Creamy Goose With Asian Greens",
    "category": "Food"
  },
  {
    "value": "food.ethnicCategory",
    "label": "Ethnic Category",
    "example": "Nepalese",
    "category": "Food"
  },
  {
    "value": "food.fruit",
    "label": "Fruit",
    "example": "dragonfruit",
    "category": "Food"
  },
  {
    "value": "food.ingredient",
    "label": "Ingredient",
    "example": "pine nut",
    "category": "Food"
  },
  {
    "value": "food.meat",
    "label": "Meat",
    "example": "beef",
    "category": "Food"
  },
  {
    "value": "food.spice",
    "label": "Spice",
    "example": "sumac",
    "category": "Food"
  },
  {
    "value": "food.vegetable",
    "label": "Vegetable",
    "example": "butternut lettuce",
    "category": "Food"
  },
  {
    "value": "git.branch",
    "label": "Branch",
    "example": "card-copy",
    "category": "Git"
  },
  {
    "value": "git.commitDate",
    "label": "Commit Date",
    "example": "Wed Jul 15 05:20:39 2026 -0500",
    "category": "Git"
  },
  {
    "value": "git.commitMessage",
    "label": "Commit Message",
    "example": "synthesize virtual protocol",
    "category": "Git"
  },
  {
    "value": "git.commitSha",
    "label": "Commit Sha",
    "example": "0dbb0be989fdedbdffe94811ea3bc01eb5d48ed7",
    "category": "Git"
  },
  {
    "value": "hacker.abbreviation",
    "label": "Abbreviation",
    "example": "SMTP",
    "category": "Hacker"
  },
  {
    "value": "hacker.adjective",
    "label": "Adjective",
    "example": "digital",
    "category": "Hacker"
  },
  {
    "value": "hacker.ingverb",
    "label": "Ingverb",
    "example": "compressing",
    "category": "Hacker"
  },
  {
    "value": "hacker.noun",
    "label": "Noun",
    "example": "matrix",
    "category": "Hacker"
  },
  {
    "value": "hacker.phrase",
    "label": "Phrase",
    "example": "Use the digital HEX monitor, then you can override the digital capacitor!",
    "category": "Hacker"
  },
  {
    "value": "hacker.verb",
    "label": "Verb",
    "example": "quantify",
    "category": "Hacker"
  },
  {
    "value": "image.avatarGitHub",
    "label": "Avatar (GitHub Style)",
    "example": "https://avatars.githubusercontent.com/u/10001",
    "category": "Image"
  },
  {
    "value": "image.avatar",
    "label": "Avatar (Random)",
    "example": "https://cloudflare-ipfs.com/ipfs/Qmd3W5D2g8nStYA7pQQWvWM27C2cZGUrkwwK7v1TRacg7L/avatar/89.jpg",
    "category": "Image"
  },
  {
    "value": "image.abstract",
    "label": "Image (Abstract)",
    "example": "https://loremflickr.com/640/480/abstract?lock=42",
    "category": "Image"
  },
  {
    "value": "image.animals",
    "label": "Image (Animals)",
    "example": "https://loremflickr.com/640/480/animals?lock=42",
    "category": "Image"
  },
  {
    "value": "image.business",
    "label": "Image (Business)",
    "example": "https://loremflickr.com/640/480/business?lock=42",
    "category": "Image"
  },
  {
    "value": "image.cats",
    "label": "Image (Cats)",
    "example": "https://loremflickr.com/640/480/cats?lock=42",
    "category": "Image"
  },
  {
    "value": "image.city",
    "label": "Image (City)",
    "example": "https://loremflickr.com/640/480/city?lock=42",
    "category": "Image"
  },
  {
    "value": "image.customCategory",
    "label": "Image (Custom Category...)",
    "example": "https://loremflickr.com/640/480/dog?lock=10",
    "category": "Image"
  },
  {
    "value": "image.fashion",
    "label": "Image (Fashion)",
    "example": "https://loremflickr.com/640/480/fashion?lock=42",
    "category": "Image"
  },
  {
    "value": "image.food",
    "label": "Image (Food)",
    "example": "https://loremflickr.com/640/480/food?lock=42",
    "category": "Image"
  },
  {
    "value": "image.urlFullHD",
    "label": "Image (Full HD 1920x1080)",
    "example": "https://picsum.photos/1920/1080?random=1",
    "category": "Image"
  },
  {
    "value": "image.urlHD",
    "label": "Image (HD 1280x720)",
    "example": "https://picsum.photos/1280/720?random=1",
    "category": "Image"
  },
  {
    "value": "image.nature",
    "label": "Image (Nature)",
    "example": "https://loremflickr.com/640/480/nature?lock=42",
    "category": "Image"
  },
  {
    "value": "image.nightlife",
    "label": "Image (Nightlife)",
    "example": "https://loremflickr.com/640/480/nightlife?lock=42",
    "category": "Image"
  },
  {
    "value": "image.people",
    "label": "Image (People)",
    "example": "https://loremflickr.com/640/480/people?lock=42",
    "category": "Image"
  },
  {
    "value": "image.sports",
    "label": "Image (Sports)",
    "example": "https://loremflickr.com/640/480/sports?lock=42",
    "category": "Image"
  },
  {
    "value": "image.urlSquare",
    "label": "Image (Square 200x200)",
    "example": "https://picsum.photos/200/200?random=1",
    "category": "Image"
  },
  {
    "value": "image.technics",
    "label": "Image (Technics)",
    "example": "https://loremflickr.com/640/480/technics?lock=42",
    "category": "Image"
  },
  {
    "value": "image.urlThumbnail",
    "label": "Image (Thumbnail 150x150)",
    "example": "https://picsum.photos/150/150?random=1",
    "category": "Image"
  },
  {
    "value": "image.transport",
    "label": "Image (Transport)",
    "example": "https://loremflickr.com/640/480/transport?lock=42",
    "category": "Image"
  },
  {
    "value": "image.personPortrait",
    "label": "Portrait (Person)",
    "example": "https://cloudflare-ipfs.com/ipfs/Qmd3W5D2g8nStYA7pQQWvWM27C2cZGUrkwwK7v1TRacg7L/avatar/22.jpg",
    "category": "Image"
  },
  {
    "value": "image.url",
    "label": "Url",
    "example": "https://picsum.photos/seed/NJ7mJgxs/531/1381",
    "category": "Image"
  },
  {
    "value": "image.urlPicsumPhotos",
    "label": "Url Picsum Photos",
    "example": "https://picsum.photos/seed/IIA5lqsE/828/1399?grayscale&blur=1",
    "category": "Image"
  },
  {
    "value": "internet.displayName",
    "label": "Display Name",
    "example": "Chelsea.Cummings75",
    "category": "Internet"
  },
  {
    "value": "internet.domainName",
    "label": "Domain Name",
    "example": "rare-widow.name",
    "category": "Internet"
  },
  {
    "value": "internet.domainSuffix",
    "label": "Domain Suffix",
    "example": "net",
    "category": "Internet"
  },
  {
    "value": "internet.domainWord",
    "label": "Domain Word",
    "example": "suburban-laughter",
    "category": "Internet"
  },
  {
    "value": "internet.email",
    "label": "Email",
    "example": "Koby63@hotmail.com",
    "category": "Internet"
  },
  {
    "value": "internet.emoji",
    "label": "Emoji",
    "example": "🇮🇹",
    "category": "Internet"
  },
  {
    "value": "internet.exampleEmail",
    "label": "Example Email",
    "example": "Duane_Cormier@example.net",
    "category": "Internet"
  },
  {
    "value": "internet.httpMethod",
    "label": "Http Method",
    "example": "PUT",
    "category": "Internet"
  },
  {
    "value": "internet.httpStatusCode",
    "label": "Http Status Code",
    "example": "302",
    "category": "Internet"
  },
  {
    "value": "internet.ip",
    "label": "Ip",
    "example": "fbfe:667a:effc:ffef:bdc3:7b75:39e3:cda3",
    "category": "Internet"
  },
  {
    "value": "internet.ipv4",
    "label": "Ipv4",
    "example": "171.110.50.57",
    "category": "Internet"
  },
  {
    "value": "internet.ipv6",
    "label": "Ipv6",
    "example": "b64c:6ed3:4ff1:bd47:8ae5:021e:cbb6:bd22",
    "category": "Internet"
  },
  {
    "value": "internet.jwtAlgorithm",
    "label": "Jwt Algorithm",
    "example": "RS512",
    "category": "Internet"
  },
  {
    "value": "internet.mac",
    "label": "Mac",
    "example": "37:31:47:f5:d4:4b",
    "category": "Internet"
  },
  {
    "value": "internet.password",
    "label": "Password",
    "example": "UzjIm17W05ccNyj",
    "category": "Internet"
  },
  {
    "value": "internet.port",
    "label": "Port",
    "example": "46661",
    "category": "Internet"
  },
  {
    "value": "internet.protocol",
    "label": "Protocol",
    "example": "http",
    "category": "Internet"
  },
  {
    "value": "internet.url",
    "label": "Url",
    "example": "https://juicy-punctuation.name",
    "category": "Internet"
  },
  {
    "value": "internet.userAgent",
    "label": "User Agent",
    "example": "Googlebot/2.1 (+http://www.google.com/bot.html)",
    "category": "Internet"
  },
  {
    "value": "internet.username",
    "label": "Username",
    "example": "Lizeth.Marks",
    "category": "Internet"
  },
  {
    "value": "location.buildingNumber",
    "label": "Building Number",
    "example": "75824",
    "category": "Location"
  },
  {
    "value": "location.cardinalDirection",
    "label": "Cardinal Direction",
    "example": "West",
    "category": "Location"
  },
  {
    "value": "location.city",
    "label": "City",
    "example": "Fort Helen",
    "category": "Location"
  },
  {
    "value": "location.continent",
    "label": "Continent",
    "example": "North America",
    "category": "Location"
  },
  {
    "value": "location.country",
    "label": "Country",
    "example": "Saudi Arabia",
    "category": "Location"
  },
  {
    "value": "location.countryCode",
    "label": "Country Code",
    "example": "AE",
    "category": "Location"
  },
  {
    "value": "location.county",
    "label": "County",
    "example": "East Sussex",
    "category": "Location"
  },
  {
    "value": "location.direction",
    "label": "Direction",
    "example": "North",
    "category": "Location"
  },
  {
    "value": "location.language",
    "label": "Language",
    "example": "{\"name\":\"Indonesian\",\"alpha2\":\"id\",\"alpha3\":\"ind\"}",
    "category": "Location"
  },
  {
    "value": "location.latitude",
    "label": "Latitude",
    "example": "25.3213",
    "category": "Location"
  },
  {
    "value": "location.longitude",
    "label": "Longitude",
    "example": "148.8792",
    "category": "Location"
  },
  {
    "value": "location.nearbyGPSCoordinate",
    "label": "Nearby G P S Coordinate",
    "example": "[-52.9742,10.0551]",
    "category": "Location"
  },
  {
    "value": "location.ordinalDirection",
    "label": "Ordinal Direction",
    "example": "Northwest",
    "category": "Location"
  },
  {
    "value": "location.postalAddress",
    "label": "Postal Address",
    "example": "Suite 976\n25802 Kertzmann Estate\nWest Luramouth\nMassachusetts\n37685",
    "category": "Location"
  },
  {
    "value": "location.secondaryAddress",
    "label": "Secondary Address",
    "example": "Suite 342",
    "category": "Location"
  },
  {
    "value": "location.state",
    "label": "State",
    "example": "Montana",
    "category": "Location"
  },
  {
    "value": "location.street",
    "label": "Street",
    "example": "Heaney Corner",
    "category": "Location"
  },
  {
    "value": "location.streetAddress",
    "label": "Street Address",
    "example": "22443 James Street",
    "category": "Location"
  },
  {
    "value": "location.timeZone",
    "label": "Time Zone",
    "example": "America/Argentina/La_Rioja",
    "category": "Location"
  },
  {
    "value": "location.zipCode",
    "label": "Zip Code",
    "example": "09364-5322",
    "category": "Location"
  },
  {
    "value": "lorem.sentence",
    "label": "Sentence",
    "example": "Cogito urbanus verecundia concido.",
    "category": "Lorem"
  },
  {
    "value": "lorem.slug",
    "label": "Slug",
    "example": "torqueo-cum-supra",
    "category": "Lorem"
  },
  {
    "value": "lorem.word",
    "label": "Word",
    "example": "contigo",
    "category": "Lorem"
  },
  {
    "value": "lorem.words",
    "label": "Words",
    "example": "voluptate vomica cariosus",
    "category": "Lorem"
  },
  {
    "value": "music.album",
    "label": "Album",
    "example": "Be",
    "category": "Music"
  },
  {
    "value": "music.artist",
    "label": "Artist",
    "example": "The Go Gos",
    "category": "Music"
  },
  {
    "value": "music.genre",
    "label": "Genre",
    "example": "Dirty South",
    "category": "Music"
  },
  {
    "value": "music.songName",
    "label": "Song Name",
    "example": "Livin' La Vida Loca",
    "category": "Music"
  },
  {
    "value": "number.bigInt",
    "label": "Big Int",
    "example": "170679822026196",
    "category": "Number"
  },
  {
    "value": "number.binary",
    "label": "Binary",
    "example": "0",
    "category": "Number"
  },
  {
    "value": "number.float",
    "label": "Float",
    "example": "0.5210104474475882",
    "category": "Number"
  },
  {
    "value": "number.hex",
    "label": "Hex",
    "example": "a",
    "category": "Number"
  },
  {
    "value": "number.int",
    "label": "Int",
    "example": "1261370743932981",
    "category": "Number"
  },
  {
    "value": "number.octal",
    "label": "Octal",
    "example": "7",
    "category": "Number"
  },
  {
    "value": "number.romanNumeral",
    "label": "Roman Numeral",
    "example": "MMMCMVII",
    "category": "Number"
  },
  {
    "value": "person.bio",
    "label": "Bio",
    "example": "streamer, person, blogger 🪰",
    "category": "Person"
  },
  {
    "value": "person.firstName",
    "label": "First Name",
    "example": "Peyton",
    "category": "Person"
  },
  {
    "value": "person.fullName",
    "label": "Full Name",
    "example": "Ryder Schamberger",
    "category": "Person"
  },
  {
    "value": "person.gender",
    "label": "Gender",
    "example": "Neither",
    "category": "Person"
  },
  {
    "value": "person.jobArea",
    "label": "Job Area",
    "example": "Accounts",
    "category": "Person"
  },
  {
    "value": "person.jobDescriptor",
    "label": "Job Descriptor",
    "example": "Legacy",
    "category": "Person"
  },
  {
    "value": "person.jobTitle",
    "label": "Job Title",
    "example": "Dynamic Interactions Facilitator",
    "category": "Person"
  },
  {
    "value": "person.jobType",
    "label": "Job Type",
    "example": "Officer",
    "category": "Person"
  },
  {
    "value": "person.lastName",
    "label": "Last Name",
    "example": "Monahan",
    "category": "Person"
  },
  {
    "value": "person.middleName",
    "label": "Middle Name",
    "example": "Oliver",
    "category": "Person"
  },
  {
    "value": "person.prefix",
    "label": "Prefix",
    "example": "Mr.",
    "category": "Person"
  },
  {
    "value": "person.sex",
    "label": "Sex",
    "example": "male",
    "category": "Person"
  },
  {
    "value": "person.sexType",
    "label": "Sex Type",
    "example": "male",
    "category": "Person"
  },
  {
    "value": "person.suffix",
    "label": "Suffix",
    "example": "MD",
    "category": "Person"
  },
  {
    "value": "person.zodiacSign",
    "label": "Zodiac Sign",
    "example": "Aries",
    "category": "Person"
  },
  {
    "value": "phone.imei",
    "label": "Imei",
    "example": "32-434066-944238-5",
    "category": "Phone"
  },
  {
    "value": "phone.number",
    "label": "Number",
    "example": "(640) 648-0673 x240",
    "category": "Phone"
  },
  {
    "value": "science.chemicalElement",
    "label": "Chemical Element",
    "example": "{\"symbol\":\"Bi\",\"name\":\"Bismuth\",\"atomicNumber\":83}",
    "category": "Science"
  },
  {
    "value": "science.unit",
    "label": "Unit",
    "example": "{\"name\":\"sievert\",\"symbol\":\"Sv\"}",
    "category": "Science"
  },
  {
    "value": "string.alpha",
    "label": "Alpha",
    "example": "g",
    "category": "String"
  },
  {
    "value": "string.alphanumeric",
    "label": "Alphanumeric",
    "example": "D",
    "category": "String"
  },
  {
    "value": "string.binary",
    "label": "Binary",
    "example": "0b1",
    "category": "String"
  },
  {
    "value": "string.hexadecimal",
    "label": "Hexadecimal",
    "example": "0x3",
    "category": "String"
  },
  {
    "value": "string.nanoid",
    "label": "Nanoid",
    "example": "QH9dbr8CuCPNpqjB8TQwi",
    "category": "String"
  },
  {
    "value": "string.numeric",
    "label": "Numeric",
    "example": "2",
    "category": "String"
  },
  {
    "value": "string.octal",
    "label": "Octal",
    "example": "0o3",
    "category": "String"
  },
  {
    "value": "string.sample",
    "label": "Sample",
    "example": "5tNKOgkf}M",
    "category": "String"
  },
  {
    "value": "string.symbol",
    "label": "Symbol",
    "example": ",",
    "category": "String"
  },
  {
    "value": "string.ulid",
    "label": "Ulid",
    "example": "01KXKCJY5V3CSSJC0ES22B68SK",
    "category": "String"
  },
  {
    "value": "string.uuid",
    "label": "Uuid",
    "example": "7e5a86bd-c455-4eff-824b-faecc55aaa4c",
    "category": "String"
  },
  {
    "value": "system.commonFileExt",
    "label": "Common File Ext",
    "example": "jpe",
    "category": "System"
  },
  {
    "value": "system.commonFileName",
    "label": "Common File Name",
    "example": "kielbasa.wav",
    "category": "System"
  },
  {
    "value": "system.commonFileType",
    "label": "Common File Type",
    "example": "audio",
    "category": "System"
  },
  {
    "value": "system.cron",
    "label": "Cron",
    "example": "* 1 * 6 5",
    "category": "System"
  },
  {
    "value": "system.directoryPath",
    "label": "Directory Path",
    "example": "/var/tmp",
    "category": "System"
  },
  {
    "value": "system.fileExt",
    "label": "File Ext",
    "example": "weba",
    "category": "System"
  },
  {
    "value": "system.fileName",
    "label": "File Name",
    "example": "since.xlw",
    "category": "System"
  },
  {
    "value": "system.filePath",
    "label": "File Path",
    "example": "/var/log/or_depute_certainly.bz2",
    "category": "System"
  },
  {
    "value": "system.fileType",
    "label": "File Type",
    "example": "application",
    "category": "System"
  },
  {
    "value": "system.mimeType",
    "label": "Mime Type",
    "example": "text/javascript",
    "category": "System"
  },
  {
    "value": "system.networkInterface",
    "label": "Network Interface",
    "example": "wwo7",
    "category": "System"
  },
  {
    "value": "system.semver",
    "label": "Semver",
    "example": "5.13.20",
    "category": "System"
  },
  {
    "value": "vehicle.bicycle",
    "label": "Bicycle",
    "example": "Tricycle",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.color",
    "label": "Color",
    "example": "blue",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.fuel",
    "label": "Fuel",
    "example": "Hybrid",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.manufacturer",
    "label": "Manufacturer",
    "example": "Cadillac",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.model",
    "label": "Model",
    "example": "ATS",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.type",
    "label": "Type",
    "example": "Extended Cab Pickup",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.vehicle",
    "label": "Vehicle",
    "example": "Chevrolet Jetta",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.vin",
    "label": "Vin",
    "example": "BU3X06VASVM568398",
    "category": "Vehicle"
  },
  {
    "value": "vehicle.vrm",
    "label": "Vrm",
    "example": "QC12WVE",
    "category": "Vehicle"
  },
  {
    "value": "word.adjective",
    "label": "Adjective",
    "example": "fluffy",
    "category": "Word"
  },
  {
    "value": "word.adverb",
    "label": "Adverb",
    "example": "quaintly",
    "category": "Word"
  },
  {
    "value": "word.conjunction",
    "label": "Conjunction",
    "example": "but",
    "category": "Word"
  },
  {
    "value": "word.interjection",
    "label": "Interjection",
    "example": "yahoo",
    "category": "Word"
  },
  {
    "value": "word.noun",
    "label": "Noun",
    "example": "schnitzel",
    "category": "Word"
  },
  {
    "value": "word.preposition",
    "label": "Preposition",
    "example": "concerning",
    "category": "Word"
  },
  {
    "value": "word.sample",
    "label": "Sample",
    "example": "overplay",
    "category": "Word"
  },
  {
    "value": "word.verb",
    "label": "Verb",
    "example": "make",
    "category": "Word"
  },
  {
    "value": "word.words",
    "label": "Words",
    "example": "transom considering",
    "category": "Word"
  }
];
