/**
 * Fack API's — TypeScript Interface Generator
 *
 * Converts JSON Schema documents into TypeScript type definitions.
 * This enables frontend developers to download exact TypeScript
 * interfaces that match the mock API's response shape, eliminating
 * synchronization drift between API contracts and frontend types.
 *
 * Pipeline:
 * ```
 * JSON Schema (from DB) → Strip x-faker keywords → Compile → TypeScript source
 * ```
 *
 * @see https://github.com/bcherny/json-schema-to-typescript
 */

import { compile } from "json-schema-to-typescript";

// ─── Types ───────────────────────────────────────────────────────────────────

/** Options for controlling the TypeScript output format */
export interface GeneratorOptions {
  /** Name for the root interface (default: "ApiResponse") */
  typeName?: string;
  /** Whether to add a banner comment (default: true) */
  bannerComment?: boolean;
  /** Whether to add `[k: string]: unknown` to interfaces (default: false) */
  additionalProperties?: boolean;
}

// ─── Generator ───────────────────────────────────────────────────────────────

/**
 * Generates a TypeScript interface from a JSON Schema document.
 *
 * Strips `x-faker` extension keywords before compilation since they
 * are not valid JSON Schema and would cause compilation warnings.
 * Also strips `format` fields that are Faker-specific.
 *
 * @param schema - A JSON Schema document (as stored in the route's responseSchema)
 * @param options - Formatting and naming options
 * @returns Generated TypeScript source code as a string
 *
 * @example
 * ```ts
 * const schema = {
 *   type: "object",
 *   properties: {
 *     id: { type: "string", format: "uuid" },
 *     name: { type: "string" },
 *     email: { type: ["string", "null"] }
 *   },
 *   required: ["id", "name"]
 * };
 *
 * const ts = await generateTypeScript(schema, { typeName: "User" });
 * // Result:
 * // export interface User {
 * //   id: string;
 * //   name: string;
 * //   email?: string | null;
 * // }
 * ```
 */
export async function generateTypeScript(
  schema: Record<string, unknown>,
  options: GeneratorOptions = {}
): Promise<string> {
  const {
    typeName = "ApiResponse",
    bannerComment = true,
    additionalProperties = false,
  } = options;

  // Strip Faker-specific extension keywords that aren't valid JSON Schema
  const cleanSchema = stripFakerKeywords(schema);

  try {
    const result = await compile(cleanSchema, typeName, {
      bannerComment: bannerComment
        ? `/**\n * Auto-generated by Fack API's\n * Do not edit manually — regenerate from the dashboard.\n * Generated at: ${new Date().toISOString()}\n */`
        : "",
      additionalProperties,
      unknownAny: false,
      strictIndexSignatures: false,
      enableConstEnums: true,
      format: true,
    });

    return result;
  } catch (error) {
    console.error("[fack-api] TypeScript generation failed:", error);
    // Return a fallback type with an error comment
    return [
      `// TypeScript generation failed: ${String(error)}`,
      `// Please check your schema configuration in the dashboard.`,
      "",
      `export interface ${typeName} {`,
      `  [key: string]: unknown;`,
      `}`,
      "",
    ].join("\n");
  }
}

// ─── Schema Cleaning ─────────────────────────────────────────────────────────

/**
 * Recursively removes `x-faker` and other Faker-specific extension
 * keywords from a JSON Schema document. These custom keywords are
 * used by the mock engine but are not valid for TypeScript compilation.
 *
 * @param obj - A JSON Schema object (or nested part thereof)
 * @returns A clean copy of the schema without Faker extensions
 */
function stripFakerKeywords(obj: Record<string, unknown>): Record<string, unknown> {
  const clean: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(obj)) {
    // Skip Faker-specific extension keywords
    if (key === "x-faker") continue;

    // Recursively clean nested objects
    if (value && typeof value === "object" && !Array.isArray(value)) {
      clean[key] = stripFakerKeywords(value as Record<string, unknown>);
    } else {
      clean[key] = value;
    }
  }

  return clean;
}
